#!/usr/bin/env bash

# Exit on error.
set -e

# Create output directory.
mkdir -p _site

# MD to HTML.
for F in ./*.md
do
	OF=${F##*/}
	tools/md2html "$F" "_site/${OF%.md}.html"
done
mv _site/README.html _site/index.html

# Compose sed command.
if [ "$(uname)" = Darwin ]; then
	SED=(sed -i '')
else
	SED=(sed -i)
fi


# Copy resources.
cp kinegram-emrtd-connector/logo-icon.svg _site/favicon.svg

# Fix links.
"${SED[@]}" 's_.md#_.html#_g' _site/*.html
"${SED[@]}" 's_.md"_.html"_g' _site/*.html
